package shape;

import java.util.*;
import java.util.stream.IntStream;

/**
 * This class represents a grid of possible IndexPairs generated by a Rectangle
 *
 * @author ari
 */
public final class Grid implements Iterable<IndexPair>
{
	// Stores the Grid as a list
	private final List<IndexPair> grid;
	// Stores the Grid as a Rectangle
	private final Rectangle<Integer> rectangle;

	/**
	 * Instantiates a new Grid. Takes a rectangle as a parameter and stores it and creates a List of all possible
	 * IndexPairs that can exist inside the Rectangle
	 *
	 * @param rectangle rectangle to create the grid based off of
	 */
	private Grid(Rectangle<Integer> rectangle)
	{
		assert rectangle != null : "Rectangle is null";

		this.rectangle = rectangle;

		// Create a new Grid in List form
		grid = new ArrayList<>();

		// For each possible x value, add each possible y value to the grid
		IntStream.range(rectangle.getBorder(Direction.LEFT), rectangle.getBorder(Direction.RIGHT)).forEach(x -> {
			// Add each possible index pair for each x to the grid
			grid.addAll(IntStream.range(rectangle.getBorder(Direction.BOTTOM),
					// Get a list of each possible index pair for each x
					rectangle.getBorder(Direction.TOP)).mapToObj(y -> new IndexPair(x, y)).toList());
		});
	}

	/**
	 * @return this grid in the form of a sorted list
	 */
	public List<IndexPair> getGridAsList()
	{
		return grid;
	}

	/**
	 * @return the grid as a Rectangle
	 */
	public Rectangle<Integer> getGridAsRectangle()
	{
		return rectangle;
	}

	/**
	 * @param rectangle creates a grid containing all possible Index Pairs from within the rectangle specified here
	 * @return a new Grid from its specified rectangle
	 */
	public static Grid from(Rectangle<Integer> rectangle)
	{
		return new Grid(rectangle);
	}

	/**
	 * @return a new Grid Iterator
	 */
	@Override
	public Iterator<IndexPair> iterator()
	{
		return new GridIterator(this);
	}

	/**
	 * @return Each IndexPair as a String separated by a space
	 */
	@Override
	public String toString()
	{
		StringBuilder stringBuilder = new StringBuilder();

		// Collect each IndexPair as a String and add them all to the StringBuilder separated by a space
		iterator().forEachRemaining(indexPair -> stringBuilder.append(indexPair).append(" "));

		// return the output from the StringBuilder while removing any trailing spaces if it exists
		return stringBuilder.substring(0, Math.max(0, stringBuilder.length() - 1));
	}

	/**
	 * GridIterator allows the Grid class to run a loop through it
	 */
	public static class GridIterator implements Iterator<IndexPair>
	{
		// Stores the current grid
		private final List<IndexPair> grid;
		// Stores the current index in the grid
		int index;

		/**
		 * Instantiates a new GridIterator
		 *
		 * @param grid the grid to instantiate
		 */
		private GridIterator(Grid grid)
		{
			this.grid = grid.grid;
			index = 0;
		}

		/**
		 * @return true if there is an IndexPair after this one and false otherwise
		 */
		@Override
		public boolean hasNext()
		{
			return grid.size() > index;
		}

		/**
		 * @return the current element in the grid and increments the index of the Grid
		 */
		@Override
		public IndexPair next()
		{
			return grid.get(index++);
		}
	}
}
